"""Build a lecture-strict re-split of the Jakob v2 detection dataset.

Added for the IEEE Access resubmission (Reviewer 2, comment 1): the published
132/33 split is by slide, so lectures leak across partitions. This script
regroups the existing v2 dataset by lecture (derived from the slide filename)
and emits a new YOLO dataset directory in which entire lectures are held out
for validation, plus the matching dataset YAML.

The lecture key is the filename with its trailing page marker (``_p01`` /
``page-0001`` etc.) and extension stripped; slides of one lecture share the
prefix. Validation lectures are chosen greedily to reach ~20% of slides while
keeping both classes present in val.

Usage (after the v2 dataset is restored under data/processed/):
    python scripts/make_lecture_strict_split.py \\
        --src data/processed/jakob_detection_v2 \\
        --dst data/processed/jakob_detection_v2_lecturestrict
Then retrain with the usual protocol, e.g.:
    python training/finetune_jakob_detector_yolo26.py \\
        --model <warm-start-v8x-checkpoint.pt> \\
        --data configs/jakob_detection_v2_lecturestrict.yaml \\
        --name v8x_lecturestrict_v1
"""

from __future__ import annotations

import argparse
import re
import shutil
from collections import defaultdict
from pathlib import Path

from loguru import logger

_PAGE_RE = re.compile(r'(_p\d+|_page[-_]?\d+|page-\d+)$', re.IGNORECASE)


def lecture_key(stem: str) -> str:
    return _PAGE_RE.sub('', stem)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--src', type=Path, default=Path('data/processed/jakob_detection_v2'))
    p.add_argument('--dst', type=Path,
                   default=Path('data/processed/jakob_detection_v2_lecturestrict'))
    p.add_argument('--val-frac', type=float, default=0.2)
    p.add_argument('--yaml-out', type=Path,
                   default=Path('configs/jakob_detection_v2_lecturestrict.yaml'))
    args = p.parse_args()

    # Collect every slide from BOTH old partitions; the re-split ignores them.
    slides = []  # (img_path, label_path)
    for part in ('train', 'val', 'test'):
        img_dir = args.src / 'images' / part
        if not img_dir.is_dir():
            continue
        for img in sorted(img_dir.iterdir()):
            if img.suffix.lower() not in ('.png', '.jpg', '.jpeg'):
                continue
            lbl = args.src / 'labels' / part / (img.stem + '.txt')
            slides.append((img, lbl if lbl.exists() else None))
    if not slides:
        logger.error(f"No images found under {args.src}/images/*")
        raise SystemExit(1)

    by_lecture = defaultdict(list)
    for img, lbl in slides:
        by_lecture[lecture_key(img.stem)].append((img, lbl))
    logger.info(f"{len(slides)} slides across {len(by_lecture)} lectures:")
    for k in sorted(by_lecture):
        logger.info(f"  {k}: {len(by_lecture[k])} slides")

    # Greedy: walk lectures smallest-first into val until ~val_frac of slides.
    target = int(round(len(slides) * args.val_frac))
    val_lectures, count = [], 0
    for k in sorted(by_lecture, key=lambda k: len(by_lecture[k])):
        if count >= target:
            break
        val_lectures.append(k)
        count += len(by_lecture[k])
    train_lectures = [k for k in by_lecture if k not in val_lectures]
    logger.info(f"val lectures ({count} slides): {val_lectures}")

    for part, lectures in (('train', train_lectures), ('val', val_lectures)):
        (args.dst / 'images' / part).mkdir(parents=True, exist_ok=True)
        (args.dst / 'labels' / part).mkdir(parents=True, exist_ok=True)
        n_img = n_lbl = 0
        for k in lectures:
            for img, lbl in by_lecture[k]:
                shutil.copy2(img, args.dst / 'images' / part / img.name)
                n_img += 1
                if lbl is not None:
                    shutil.copy2(lbl, args.dst / 'labels' / part / lbl.name)
                    n_lbl += 1
        logger.info(f"{part}: {n_img} images, {n_lbl} label files")

    args.yaml_out.parent.mkdir(parents=True, exist_ok=True)
    args.yaml_out.write_text(
        "# Lecture-strict re-split of jakob_detection_v2 (Reviewer 2, comment 1)\n"
        f"# Generated by scripts/make_lecture_strict_split.py; val lectures: {val_lectures}\n"
        f"path: {args.dst.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n\n"
        "nc: 2\n"
        "names: ['text', 'math']\n",
        encoding='utf-8',
    )
    logger.info(f"Wrote {args.yaml_out}")


if __name__ == '__main__':
    main()
