"""Poll for YOLO26 training completion and write a comparison note.

Spawned as a detached background process on 2026-05-20 so the user has a
ready-made summary when they come back. Polls every 60s for the training
summary JSON; when found, compares against the v8x hires baseline and
writes notes/yolo26_post_training_report.md.
"""

from __future__ import annotations

import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / 'runs/detect/runs/jakob_detector_v3/yolo26x_v1/training_summary.json'
LOG = ROOT / 'logs/finetune_yolo26x.log'
REPORT = ROOT / 'notes/yolo26_post_training_report.md'


def _baseline_map50() -> str:
    """Read the v8x hires baseline mAP50 from its summary if available."""
    cand = ROOT / 'runs/detect/runs/jakob_detector_v3/hires1536/training_summary.json'
    if not cand.exists():
        cand = ROOT / 'runs/jakob_detector_v3/hires1536/training_summary.json'
    if cand.exists():
        try:
            d = json.load(open(cand))
            v = d.get('mAP50') or d.get('mAP50_95')
            return f"{v:.4f}" if isinstance(v, (int, float)) else 'n/a'
        except Exception:
            return 'n/a'
    return '~0.54 (CLAUDE.md cited)'


def _last_val_rows(n: int = 5):
    if not LOG.exists():
        return []
    rows = []
    with open(LOG, errors='replace') as f:
        for line in f:
            if 'all' in line and line.lstrip().startswith('all'):
                parts = line.split()
                if len(parts) >= 7:
                    rows.append(parts)
    return rows[-n:]


def main():
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    start = time.time()
    while not SUMMARY.exists():
        if time.time() - start > 6 * 3600:
            REPORT.write_text(
                f"# YOLO26 watcher gave up after 6 h.\n\n"
                f"Summary file never appeared at `{SUMMARY}`.\n"
                f"Training process may have died — check `logs/finetune_yolo26x.log`.\n",
                encoding='utf-8',
            )
            return
        time.sleep(60)

    summary = json.load(open(SUMMARY))
    val_rows = _last_val_rows(5)
    baseline = _baseline_map50()

    map50 = summary.get('mAP50')
    map5095 = summary.get('mAP50_95')
    delta = (map50 - 0.54) if isinstance(map50, (int, float)) else None
    verdict = ''
    if isinstance(map50, (int, float)):
        if map50 > 0.54:
            verdict = (f"**YOLO26x beat the v8x hires baseline by "
                       f"{(map50 - 0.54) * 100:.1f} points** — switch the "
                       f"detector path in `infer.py` to use this run.")
        elif map50 > 0.45:
            verdict = (f"YOLO26x came close to the v8x baseline ({map50:.3f} "
                       f"vs 0.54) but didn't beat it. The honest paper story: "
                       f"checkpoint continuity matters more than architecture "
                       f"at n=165 slides.")
        else:
            verdict = (f"YOLO26x underperformed the v8x baseline by "
                       f"{(0.54 - map50) * 100:.1f} points. Likely cause: "
                       f"training from COCO weights vs v8x's warm-start from a "
                       f"v2 Jakob checkpoint. Architecture upgrade does not "
                       f"compensate for the warm-start at this dataset size.")

    lines = [
        '# YOLO26x post-training report',
        '',
        f'Auto-generated by `scripts/watch_yolo26_training.py` on '
        f'{time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())}.',
        '',
        '## Headline',
        '',
        f'- **mAP50**:    `{map50}`',
        f'- **mAP50-95**: `{map5095}`',
        f'- **v8x hires baseline**: `{baseline}`',
        '',
        verdict,
        '',
        '## Run config',
        '',
        '```json',
        json.dumps(summary, indent=2),
        '```',
        '',
        '## Last 5 validation rows from the log',
        '',
        '```',
        f'{"":<8}{"P":>7}{"R":>7}{"mAP50":>9}{"mAP50-95":>11}',
    ]
    for r in val_rows:
        try:
            p, rcl, m50, m5095 = r[-4:]
            lines.append(f'  all   {p:>7}{rcl:>7}{m50:>9}{m5095:>11}')
        except Exception:
            pass
    lines += [
        '```',
        '',
        '## Files',
        '',
        f'- Best weights: `{summary.get("best_weights", "?")}`',
        f'- Full log:     `logs/finetune_yolo26x.log`',
        f'- Run dir:      `{summary.get("save_dir", "?")}`',
        '',
        '## Next steps',
        '',
        '1. If mAP50 > 0.54, swap the detector path in `infer.py` calls:',
        f'   `--detector-path {summary.get("best_weights", "?")}`',
        '2. Reconcile branches: `git fetch origin && git merge origin/main` '
        '(was diverged after the Mac\'s 46a95e3 commit on `main`).',
        '3. Update [[session-2026-05-20-yolo26-training]] memory with the '
        'final number.',
        '4. Continue with gap 3 (`docs/gap3_cross_professor_plan.md`).',
    ]
    REPORT.write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    main()
